### ISSUE TITLE
New wall turrets

### ISSUE THREAD

**Issue by ghost** [3Snake3/Sapphirium#2]
Ice cube wall turret: Fires frag ice bullets, 2x2
Graphite wall: 450 hp, 1x1
Large Graphite Wall: 650 hp, 2x2
Graphite Wall Turret: Fires gray lasers, 2x2
You don't have to add these, because they are only suggestions.

**Comment by 3Snake3** [comment]
It's a good idea, I'll think about it. Thank you :)
