### ISSUE TITLE
The mass driver broken

### ISSUE THREAD

**Issue by DatOnePlayer** [3Snake3/Sapphirium#3]
Mass driver broken and cannot be used

**Comment by DatOnePlayer** [comment]
@3Snake3

**Comment by 3Snake3** [comment]
What build are you currently playing on?
The mod is currently playable so far only on 126.2

**Comment by 3Snake3** [comment]
@DatOnePlayer

**Comment by DatOnePlayer** [comment]
Pre alpha?

**Comment by DatOnePlayer** [comment]
@3Snake3

**Comment by DatOnePlayer** [comment]
Alright, how about in Bleeding Edge?

**Comment by DatOnePlayer** [comment]
@3Snake3 also let me know when it is fixed

**Comment by 3Snake3** [comment]
I successfully fixed the mod. It is now playable on 7.0 builds. Good luck.

**Comment by 3Snake3** [comment]
@DatOnePlayer

**Comment by DatOnePlayer** [comment]
Thanks a lot mate @3Snake3
