### ISSUE TITLE
Freezer crash

### ISSUE THREAD

**Issue by DatOnePlayer** [3Snake3/Sapphirium#4]
@3Snake3 viewing information of Freezer block (freezes liquids) exits the Bleeding Edge and Pre Alpha version

**Comment by 3Snake3** [comment]
The crash occurs due to multi-lib.js and since I didn't create this lib, I turned to the author with this question and am currently waiting for an answer.

**Comment by 3Snake3** [comment]
@DatOnePlayer

**Comment by DatOnePlayer** [comment]
Alright let me know when it is fixed @3Snake3

**Comment by DatOnePlayer** [comment]
@3Snake3 any progress?

**Comment by 3Snake3** [comment]
@DatOnePlayer According to the author, multi-lib is outdated and is unlikely to be updated, unfortunately. In this case, I will have to split the Freezer into 4 blocks that will freeze a certain liquid.

**Comment by 3Snake3** [comment]
@DatOnePlayer Here's what the author said: "I serve militery because of korean duty. This mod won't be updated well. As crafter-related things aren't change much in mindustry, this mod won't be oudated fastly"

**Comment by DatOnePlayer** [comment]
@3Snake3 okay then, I guess I should wait for this one tho, wish you could update that sooner for the freezer blocks

**Comment by 3Snake3** [comment]
@DatOnePlayer To be honest, I don't understand complex js or java functions myself yet, so I'm unlikely to be able to fix something myself.

**Comment by DatOnePlayer** [comment]
No, I mean I am waiting for you to separate them to individual blocks though
No rush though

**Comment by DatOnePlayer** [comment]
@3Snake3

**Comment by 3Snake3** [comment]
@DatOnePlayer In the upcoming update.

**Comment by 3Snake3** [comment]
@DatOnePlayer I fixed the Multi Crafter. Now it works correctly. I will release update soon.
